### ISSUE TITLE
CI migration

### ISSUE THREAD

**Issue by davetapley** [JEFuller/Piexif#5]
# Appveyor

## Inherited

https://github.com/JEFuller/Piexif/blob/3422fbe7a12c3ebcc90532d8e1f4e3be32ece80c/appveyor.yml

https://ci.appveyor.com/project/hMatoba/piexif/history

Last pass Nov 2020: https://ci.appveyor.com/project/hMatoba/piexif/builds/36156177

## Migration

Moved to https://ci.appveyor.com/project/davetapley/piexif

# Travis

## Inherited

https://github.com/hMatoba/Piexif/blob/3422fbe7a12c3ebcc90532d8e1f4e3be32ece80c/.travis.yml

No history: https://app.travis-ci.com/github/hMatoba/Piexif/builds

## Migration

Moved to https://app.travis-ci.com/github/JEFuller/Piexif

But:
> We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution.

~awaiting response from Support <support@travis-ci.com>~
awaiting OSS build credits from Support <support@travis-ci.com>

[Able to trigger build but lots of failures](https://app.travis-ci.com/github/JEFuller/Piexif/builds/256218198) :x:

# Coveralls

https://coveralls.io/github/hMatoba/Piexif

Last build Nov 2020: https://coveralls.io/builds/34747634

Triggered from:
https://github.com/JEFuller/Piexif/blob/3422fbe7a12c3ebcc90532d8e1f4e3be32ece80c/.travis.yml#L22-L23

Not not sure how when no Travis history 🤔

**Comment by hartwork** [comment]
Hi!

In reply to https://github.com/JEFuller/Piexif/issues/1#issuecomment-1374672884, I would like to summarize what I see in the existing CI files linked above:
- CPython 2.7, 3.5, 3.7, 3.8, pypy3
- Linux and Windows
- Tests suite run
- Coveralls upload

I suggest to:
- First clarify what of that is still needed, no longer needed, or needed more and then
- re-write that with GitHub Actions, because fast, free, potent, well-integrated, here to stay.

I'd like to add a personal vote for dropping Python 2.7 and 3.5 because of end-of-life.
What do you think, what are the requirements?

**Comment by davetapley** [comment]
@hartwork sorry I missed this 😊 

* I concur that GitHub Actions rewrite is best. I'll abandon appveyor and Travis and work on that 
* I'll see if 2.7 and 3.5 still work, but yes I think it's appropriate to drop them if they cause trouble

**Comment by hartwork** [comment]
> * I concur that GitHub Actions rewrite is best. I'll abandon appveyor and Travis and work on that

@davetapley cool!

> * I'll see if 2.7 and 3.5 still work, but yes I think it's appropriate to drop them if they cause trouble

Not sure about trouble but surely cost, both CI and human: Everything before 3.7 is dead: https://endoflife.date/python

**Comment by djjudas21** [comment]
Hey @davetapley, how are you getting on with this?

**Comment by davetapley** [comment]
@djjudas21 haven't even started, but I can make time to merge PRs!

**Comment by davetapley** [comment]
#7
